config/routes.rb
Rails.application.routes.draw do
    root to: 'articles#index' #Tells app to start on our articles index page
    resources :articles do
        resources :comments
    end
    resources :tags
    resources :authors
    resources :author_sessions, only: [ :new, :create, :destroy]
    
    get 'login' => 'author_sessions#new'
    get 'logout' => 'author_sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments,
    dependent: :destroy #ensures that when we call destroy on article it'll destroy comments too
    has_many :taggings,
    dependent: :destroy
    has_many :tags, through: :taggings
    has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>"} #has_attached_file is part of paperclip library, paperclip understands this model should accept a file attachement and store info in model's database
    validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

    
    def tag_list=(tags_string)
        tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
        new_or_found_tags = tag_names.collect{ |name| Tag.find_or_create_by(name: name)}
        self.tags = new_or_found_tags
    end
    
    def tag_list
        self.tags.collect do |tag|
            tag.name
        end.join(", ")
    end
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings,
    dependent: :destroy 
    has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_login, except: [:index, :show]
    
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
        #Views counter Logic
        a = @article.viewCount += 1
        @article.update_attribute "viewCount", a
        #
        @comment = Comment.new
        @comment.article_id = @article.id
    end
    
    def create
        @article = Article.new(article_params)
        @article.viewCount = 0;
        @article.save
        flash.notice = "Article '#{@article.title}' created!"
        
        redirect_to article_path(@article)
    end
    
    def new
        @article = Article.new
    end
    
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        flash.notice = "Article '#{@article.title}' removed."
        
        redirect_to articles_path
    end
    
    #Like new sends form data to create, edit sends form data to update
    def edit
        @article = Article.find(params[:id])
    end
    
    def update
        @article = Article.find(params[:id])
        @article.update(article_params)
        flash.notice = "Article '#{@article.title}' updated!"
        
        redirect_to article_path(@article)
    end
    
    def article_params
        params.require(:article).permit(:title, :body, :tag_list, :image)
    end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
    def new
    end
    
    def create
        if login(params[:email], params[:password])
            redirect_back_or_to(articles_path, notice: "Logged in successfully")
        else
            flash.now.alert = "Login attempt failed"
            redirect_to(login_path, notice: "Login attempt failed")
        end
    end
    
    def destroy
        logout
        redirect_to(:authors, notice: "Logged out")
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end


before_action :zero_authors_or_authenticated, only: [:new, :create] #Tells it to run zero_authors_or_authenticated before the new and create methods i.e if false, they're refused access to create articles
  
  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user #Unless there's no authors or there's a current user
      flash.notice = "You do not have permission to create a new Author."
      redirect_to root_path
      return false
    end
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_action :require_login, except: [:create] 
   
    def create 
        @comment = Comment.new(comment_params)
        @comment.article_id = params[:article_id]
        
        @comment.save
        # After creating comment, redirect to article show page
        redirect_to article_path(@comment.article)
    end
    
     def destroy
        @comment = Comment.find(params[:id])
        @comment.destroy
        flash.notice = "Comment removed."
        
        redirect_to article_path(@comment.article_id)
    end
    
    
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
   before_action :require_login, only: [:destroy]
   
    def show
        @tag = Tag.find(params[:id])
    end
    
    def index
        @tags = Tag.all
    end
    
    def destroy
        @tag = Tag.find(params[:id])
        @tag.destroy
        flash.notice = "Tag '#{@tag.name}' removed."
        
        redirect_to tags_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
     def article_params
    params.require(:article).permit(:title, :body, :tag_list, :image)
  end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div style="padding: 10px; background: white; margin: 10px auto; border-radius: 5px;">
    <h5 style="margin-top: 10px;">Comment by <%= comment.author_name %>:</h5>
    <p style="font-size: 12px;"><%= comment.body %></p>
    <p style="color: gray; font-size: 10px;">Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at)%> later</p>
    <% if logged_in? %>
        <button><%= link_to "delete", [@article, comment], method: :delete, data: {confirm: "Really delete the comment?"} %></button>
    <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %> <!--Multipart data is now accepted, this will handle the images-->
    <ul>
        <% @article.errors.full_messages.each do |error| %>
        <li><%= error %></li>
        <% end %>
    </ul>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title, class: "form", :required => true %>
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body, class: "form form-body" %>
    </p>
    <p>
        <% if @article.image.exists? %> <!--If an image file is already attached, show it -->
            <%= image_tag @article.image.url(:medium) %><br /> <!--passing medium image size from article model where image styles are-->
        <% end %>
        <%= f.label :image, "Attach a New Image" %><br />
        <%= f.file_field :image %>
        
    </p>
    <p>
        <%= f.label :tag_list %><br />
        <%= f.text_field :tag_list, class: "form" %>
    </p>
    <p>
        <%= f.submit "Submit", class: "submit" %>
    </p>
    <% end %>

app/views/articles/edit.html.erb
<div class="heading">
    <h1>Edit an Article</h1>    
</div>

<div class="mainSection">
    <%= render partial: "form" %>    
</div>

app/views/articles/index.html.erb
<div class="heading">
    <h1>All Articles</h1>    
</div>
<div class="mainSection">
    <ul id="articles">
    <% @articles.each do |article| %>
    <li>
        <%= link_to article.title, article_path(article) %>
    </li>
    <% end %>
</ul>
<button style="background: #60656F;"><%= link_to "View All Tags", tags_path %></button>
<% if logged_in? %>
<button style="background: #279AF1;"><%= link_to "Create a New Article", new_article_path, class: "new_article" %></button>
<% end %>    
</div>

<!--Only show if logged in-->

app/views/articles/new.html.erb
<div class="heading">
    <h1>Create a New Article</h1>
</div>

<!-- Rendering form from _form.html.erb partial -->
<div class="mainSection">
    <%= render partial: "form" %>    
</div>

app/views/articles/show.html.erb
    <div class="heading">
        <h1><%= @article.title %></h1>
    </div>
    <div class="mainSection">
        <p style="color: gray;">Views: <%= @article.viewCount %></p>
        <p style="color: gray;">
        Tags:
        <% @article.tags.each do |tag| %>
            <%= link_to tag.name, tag_path(tag) %>
        <% end %>
    </p>
    <p>
        <% if @article.image.exists? %>
            <%= image_tag @article.image.url, class: "image" %>
        <% end %>
    </p>
    <p><%= @article.body %></p>
    
    <h4>Comments (<%= @article.comments.size %>)</h4>
    <%= render partial: "articles/comment", collection: @article.comments %> <!-- Tells that we want to render a partial named comment and want to do it once for each element in the collection @article.comments -->
    <% if logged_in? %>
    <hr>
    <button style="background: #ed9121;"><%= link_to "edit article", edit_article_path(@article) %></button>
    <button style="background: #ff5c5c;"><%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Really delete the article?"} %></button>
    <% end %>
    <!--No one can see edit or delete article links if not logged in and authorized -->
    <%= render partial: 'comments/form' %>
    <%= link_to "Back to Articles List", articles_path %>     
    </div>

        

app/views/author_sessions/new.html.erb
<div class="heading">
    <h1>Login</h1>    
</div>

<div class="mainSection">
    <%= form_tag author_sessions_path, method: :post do%>
    
        <%= label_tag :email %>
        <%= text_field_tag :email %>
        <br />
    
    
        <%= label_tag :password %>
        <%= password_field_tag :password %>
        <br />
    <div class="actions">
        <%= submit_tag "Login", class: "submit" %>
    </div>
    <% end %>
    
<%= link_to 'Back', articles_path %>    
</div>

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Password confirmation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h4>Post a comment</h4>
 <%= form_for [@article, @comment] do |f| %>
    <p>
        <%= f.label :author_name, "Your Name" %><br />
        <%= f.text_field :author_name, class: "form", :required => true %> <!--HTML5 require attr to make sure can't be submitted blank-->
    </p>
    <p>
        <%= f.label :body, "Your Comment" %><br />
        <%= f.text_area :body, class: "form form-body", :required => true %>
    </p>
    <p>
        <%= f.submit 'Submit', class: "submit" %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('ruby.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Bowlby+One+SC|Comfortaa|Lobster|Montserrat" rel="stylesheet">
  </head>

  <body>
    <div id="navBar">
      <a href="/"><h2 style="position: absolute; left: 10px; font-family: 'Montserrat', sans-serif; color: #fafafa; top: -10px;">RailsBlog</h2>
        <p class="gem"><i class="fas fa-gem"></i></p>
      </a>
      <h6>
          <% if logged_in? %>
            <%= "Logged in as #{current_user.username}" %>
            <%= link_to "(logout)", logout_path %>
          <% else %>
            <%= link_to "(login)", login_path %>
          <% end %>
        </h6>
    </div>
      <p class='flash'><%= flash.notice %></p>
        <div class="mainContain">
           <%= yield %>
        </div>
      
    
  </body>
</html>

app/views/tags/index.html.erb
<div class="heading">
    <h1>All Tags</h1>    
</div>

<div class="mainSection">
    <ul>
    <% @tags.each do |tag| %>
    <li>
        <%= link_to tag.name, tag_path(tag) %>
        <button style="background: #ff5c5c; float: right;"><%= link_to "delete", tag_path(tag), method: :delete, data: {confirm: "Really delete the tag?"} %> <%= tag.name%></button>
    </li>
    <% end %>
</ul>
<button style="background: #60656F;"><%= link_to "Back to Articles", articles_path%></button>    
</div>

app/views/tags/show.html.erb
<div class="heading">
    <h1>Articles Tagged with '<%= @tag.name %>'</h1>    
</div>
<div class="mainSection">
    <ul>
    <% @tag.articles.each do |article| %>
        <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
</ul>
    
</div>